-- 코드를 입력하세요
SELECT B.AUTHOR_ID
     , A.AUTHOR_NAME
     , B.CATEGORY
     , SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES BS
WHERE B.AUTHOR_ID = A.AUTHOR_ID
  AND B.BOOK_ID = BS.BOOK_ID
  AND BS.SALES_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2022-01-31', 'YYYY-MM-DD')
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;