-- 코드를 입력하세요
SELECT FOOD_TYPE
     , REST_ID
     , REST_NAME
     , FAVORITES
FROM REST_INFO A
WHERE FAVORITES = 
      (
          SELECT MAX(FAVORITES)
          FROM REST_INFO
          WHERE FOOD_TYPE = A.FOOD_TYPE
          GROUP BY FOOD_TYPE
      )
ORDER BY FOOD_TYPE DESC;