-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH
     , CAR_ID
     , COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
HAVING COUNT(*) != 0 AND 
(
    SELECT COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID = A.CAR_ID
      AND START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
) >= 5
ORDER BY MONTH, CAR_ID DESC;