-- 코드를 입력하세요
SELECT B.TITLE AS TITLE
     , B.BOARD_ID AS BOARD_ID
     , R.REPLY_ID AS REPLY_ID
     , R.WRITER_ID AS WRITER_ID
     , R.CONTENTS AS CONTENTS
     , TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B
   , USED_GOODS_REPLY R
WHERE B.BOARD_ID = R.BOARD_ID
  AND B.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
ORDER BY CREATED_DATE ASC, TITLE ASC;